## データ型の確認

In [ ]:
import numpy as np

d = np.array([1, 2], dtype=np.int16)
# 型を確認する
type(d) 
# データの型を確認する
d.dtype

## 乱数の生成

In [ ]:
# 乱数を生成するインスタンス
rng = np.random.default_rng()
# 3行2列の乱数を生成する
f = rng.random((3, 2))
# 1から10の整数を生成する
rng.integers(1, 10)
# 1から10の整数を3行3列の配列で生成する
rng.integers(1, 10, size=(3, 3))
# 0.0から5.0の範囲で2行3列の一様分布を生成する
rng.uniform(0.0, 5.0, size=(2, 3))
# 0.0から1.0の範囲で4行3列の一様分布を生成する
rng.uniform(size=(4, 3))
# 標準正規分布の乱数を生成する
rng.standard_normal(size=(4, 2))
# 平均50、標準偏差10の正規分布の乱数を生成する
rng.normal(50, 10, 3)

## 要素内の差分

In [6]:
l1 = np.array([2, 2, 6, 1, 3])
np.diff(l1)

array([ 0,  4, -5,  2])

## 連結

In [ ]:
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])
# 配列を結合する
np.concatenate([a1, a2])
# 配列を行結合する
np.concatenate([a1, a2], axis=0)
np.hstack([a1, a2])
# 配列を列結合する
np.concatenate([a1, a2], axis=1)
np.vstack([a1, a2])

## 分割

In [21]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
first, second = np.split(a, [2], axis=1)
first

array([[1, 2],
       [5, 6]])

In [22]:
second

array([[3, 4],
       [7, 8]])

## 次元追加



In [ ]:
a = np.array([1, 2, 3, 4])
# 配列を1列にする
a[:, np.newaxis]
# 配列を1行にする
a[np.newaxis, :]

array([[1],
       [2],
       [3],
       [4]])

## グリッドデータの生成

In [29]:
# 0から3の配列を生成する
m = np.arange(0, 4)
# 4から7の配列を生成する
n = np.arange(4, 8)
# 2次元配列を生成する
xx, yy = np.meshgrid(m, n)
# 行方向の配列を表示する
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
# 列方向の配列を表示する
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

## ユニバーサル関数

In [ ]:
b = np.arange(-3, 3).reshape((2, 3))
# 絶対値を計算する
np.abs(b)

array([[3, 2, 1],
       [0, 1, 2]])