# NumPyでデータを扱う

In [ ]:
import numpy as np

d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [ ]:
# 型を変換する
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [ ]:
# 乱数を生成するインスタンス
rng = np.random.default_rng()
# 3行2列の乱数を生成する
f = rng.random((3, 2))
f

array([[0.60804369, 0.57236755],
       [0.55935703, 0.73049259],
       [0.06328987, 0.06467662]])