# NumPyでデータを扱う

In [ ]:
import numpy as np

d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [ ]:
# 型を変換する
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [ ]:
# 乱数を生成するインスタンス
rng = np.random.default_rng()
# 3行2列の乱数を生成する
f = rng.random((3, 2))
f

array([[0.60804369, 0.57236755],
       [0.55935703, 0.73049259],
       [0.06328987, 0.06467662]])

In [7]:
rng = np.random.default_rng(123)
f = rng.random((3, 2))
f

array([[0.68235186, 0.05382102],
       [0.22035987, 0.18437181],
       [0.1759059 , 0.81209451]])

In [11]:
rng = np.random.default_rng(123)
# 1から10の整数を生成する
rng.integers(1, 10)

np.int64(1)

In [12]:
rng = np.random.default_rng(123)
rng.integers(1, 10, size=(3, 3))

array([[1, 7, 6],
       [1, 9, 2],
       [3, 2, 4]])

In [ ]:
rng = np.random.default_rng(123)
# 0.0から5.0の範囲で2行3列の乱数を生成する
# uniformは一様分布
rng.uniform(0.0, 5.0, size=(2, 3))

In [13]:
rng = np.random.default_rng(123)
rng.uniform(size=(4, 3))

array([[0.68235186, 0.05382102, 0.22035987],
       [0.18437181, 0.1759059 , 0.81209451],
       [0.923345  , 0.2765744 , 0.81975456],
       [0.88989269, 0.51297046, 0.2449646 ]])

In [ ]:
rng = np.random.default_rng(123)
# 標準正規分布の乱数を生成する
rng.standard_normal(size=(4, 2))

array([[-0.98912135, -0.36778665],
       [ 1.28792526,  0.19397442],
       [ 0.9202309 ,  0.57710379],
       [-0.63646365,  0.54195222]])

In [16]:
rng = np.random.default_rng(123)
# 平均50、標準偏差10の正規分布の乱数を生成する
rng.normal(50, 10, 3)

array([40.1087865 , 46.32213349, 62.87925261])

In [17]:
np.full(3, 3.14)

array([3.14, 3.14, 3.14])

In [18]:
l = np.array([2, 2, 6, 1, 3])
np.diff(l)

array([ 0,  4, -5,  2])

In [ ]:
# 配列を結合する
np.concatenate([a, a1])

NameError: name 'a' is not defined

In [19]:
np.concatenate([a, a1])

NameError: name 'a' is not defined

In [21]:
a=np.array([1, 2, 3])

In [22]:
# 配列を1行にする
a[np.newaxis, :]

array([[1, 2, 3]])

In [23]:
# 配列を1列にするc
a[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [27]:
m = np.arange(0, 4)
n = np.arange(4, 8)
# 2次元配列を生成する
xx, yy = np.meshgrid(m, n)
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [28]:
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])