# NumPyの各機能

In [ ]:
import numpy as np

a = np.arange(3)
b = np.arange(-3, 3).reshape((2, 3))
c = np.arange(1, 7).reshape((2, 3))
d = np.arange(6).reshape((3, 2))
e = np.linspace(-1, 1, 10)
print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)
print("e:", e)

a: [0 1 2]
b: [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [2]:
li = [[-3, -2, -1],
      [0, 1, 2]]
new = []
for i, j in enumerate(li):
    # 新しいリストを作成する
    new.append([])
    for k in j:
        # 絶対値を計算する
        new[i].append(abs(k))
new

[[3, 2, 1], [0, 1, 2]]

In [ ]:
# 絶対値を計算する
np.abs(b)

In [ ]:
# 三角関数を計算する
np.sin(e)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])