# NumPyの各機能

In [ ]:
import numpy as np

a = np.arange(3)
b = np.arange(-3, 3).reshape((2, 3))
c = np.arange(1, 7).reshape((2, 3))
d = np.arange(6).reshape((3, 2))
e = np.linspace(-1, 1, 10)
print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)
print("e:", e)

a: [0 1 2]
b: [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [2]:
li = [[-3, -2, -1],
      [0, 1, 2]]
new = []
for i, j in enumerate(li):
    # 新しいリストを作成する
    new.append([])
    for k in j:
        # 絶対値を計算する
        new[i].append(abs(k))
new

[[3, 2, 1], [0, 1, 2]]

In [ ]:
# 絶対値を計算する
np.abs(b)

In [ ]:
# 三角関数を計算する
np.sin(e)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [4]:
np.log(a)

C:\Users\matsu\AppData\Local\Temp\ipykernel_15896\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718])

In [5]:
np.log10(c)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [6]:
# 指数関数(eのx乗)を計算する
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [7]:
a1 = a[:, np.newaxis]
a1

array([[0],
       [1],
       [2]])

In [ ]:
# 配列の要素ごとの和を計算する
a + a1
# 0+0=0, 1+1=2, 2+2=4
# 1+0=1, 1+1=2, 2+2=3
# 2+0=2, 2+1=3, 2+2=4

In [8]:
c - np.mean(c)

array([[-2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5]])

In [9]:
b ** 3

array([[-27,  -8,  -1],
       [  0,   1,   8]])

In [ ]:
# 配列の要素ごとの0でない要素の数を数える
np.count_nonzero(b > 0)

2